### ISSUE TITLE
Client for Android?!

### ISSUE THREAD

**Issue by landim32** [inspirer/mibew#23]
Is there any project to a version mibew for android?
I would like to join or start a project this.

Someone?!

**Comment by chrispecoraro** [comment]
The first step would be to create a dashboard with HTML5 boilerplate mobile or similar.  Then use media queries to adapt to the smaller screen.

**Comment by alberto234** [comment]
Hello chrispecoraro / landim32, 

The approach of using HTML5 would be good, as the dashboard will be conveniently displayed on every screen size with the media queries. The visitors will also benefit from a theme that uses the same concepts, as the current default theme is not mobile friendly.

My preference for developing native Android apps however led me the other way. If you are still interested, I published the Mibew Mobile app to the Google Play store. Search there or visit the app's main page at http://mibewmob.scalior.com.

Eyong
